# Generated by Django 3.2.6 on 2021-08-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Api', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('Auth', models.CharField(default=None, max_length=100)),
                ('HTTPS', models.CharField(max_length=5)),
                ('Link', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100)),
            ],
        ),
    ]
