# Generated by Django 3.2.6 on 2021-08-27 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='Cors',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
