# Generated by Django 3.2.6 on 2021-08-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_subcategory_cors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Api',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Description',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='HTTPS',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Link',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
