# Generated by Django 3.2.6 on 2021-08-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20210827_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='Api',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Auth',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Cors',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='Description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='HTTPS',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
